### ISSUE TITLE
Optimization: Executing multiple same SQL simultaneously

### ISSUE THREAD

**Issue by domechn** [tellery/tellery#107]
When multiple people execute the same SQL at the approach time, the backend should not send all of them to the connector. But only once then return the result to all requests.

**Describe the solution you'd like**

- Calculate the `Hash` of SQL needs to be executed
- Place Hash in a global storage ( pg or redis )
- Before performing a SQL, first check the store to confirm if the SQL is currently being executed.
    - If the SQL is not being executed, submit it to the Connector and store it
    - If the SQL is being executed, waiting until the previous SQL is completed and return the result

**Additional context**

We need to take into account the expansion of Backend. Thus we need to save the results of SQL to global storage. Let the waiting request can get this result.

Maybe we can set an `Index` for each Pending SQL. When there is a executing sql request, make the Pending SQL's index plus 1. When the Pending request gets SQL Result, make the Pending SQL's index sub 1.

If the Index is 0, delete the Pending SQL Record.

**Comment by raycursive** [comment]
There is another approach: just based on our broadcast of the change of block, once an SQL execution has been submitted, check if its block Id is in the Redis. If so, just drop the execution and wait for the event notifying the user that the block has been changed.

The only problem of this approach is that canceling query may not work properly, (since by such a design, only the first user executing SQL is able to cancel the query.

If we thought the cost of re-run a query is always affordable, the latter approach should work well IMO
