### ISSUE TITLE
Unexcepted No Permissions Error when using global search

### ISSUE THREAD

**Issue by domechn** [tellery/tellery#330]
**Describe the bug**
see the issue title

**To Reproduce**
1. Go to https://demo.tellery.io
2. Click `Command+k`
3. Input `te`

**Screenshots**
![9633B237-1DFD-481F-864F-E0F9C225A15D](https://user-images.githubusercontent.com/31119455/131983816-283b58a1-b7b7-4bcf-b7eb-39e75341cece.png)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [online demo]

**Comment by domechn** [comment]
@raycursive

**Comment by raycursive** [comment]
Seems like the result of global search returned stories that users have no access.

I'll fix it later my bro

**Comment by raycursive** [comment]
fixed at this [commit](https://github.com/tellery/tellery/commit/2e06d7226f8284e78da92e48ee9536d7aedffa96)
(My bad, forgot to checkout a new branch. T_T

This issue comes with the *duplicate story*, it copies all blocks in the source story, including its permission.
Those permissions should be reset by frontend. cc @cosformula 

Currently I added a post-filter to ensure that returned search result contains no unpermitted content, but it will cause that the number of returned data is different from the given `limit`.
